### ISSUE TITLE
quotation marks are force at integers

### ISSUE THREAD

**Issue by juxbru** [particledecay/ansible-jsonpatch#21]
I've a json with like this:
 {
    "bla": 3,
    "devices": [
        {
            "dummy": "/var"
        },
        {
            "tempdir": "/var/temp",
            "memlimit": 100,
            "units": 50
        }
    ]
}

and try to change the unit value from 50 to 250 with following ansible code:

- name: "manage json file test"
  json_patch:
    src: "{{ src }}"
    dest: "{{ dest }}"
    pretty: yes
    operations:
      - op: replace
        path: devices/1/units
        value: 250

but regardless of how I write the value, the result is always **"units": "250"** (with quotation marks around the integer). If I replace the whole inner curly bracket (tempdir, memlimit, units) like this:

path: devices/1
value: '{ "tempdir": "/var/temp", "memlimit": 100, "units": 250 }'

it works. But I think there must be a way to output a number without quotation marks, right?
(sorry, I haven't figured out how to make indentations here)

**Comment by particledecay** [comment]
Sorry, not sure why I didn't see this issue until now. Is this still an issue for you? Generally speaking, it's tough to make assumptions about data types in JSON. In this case, YAML is converting to Python data type of string because Ansible obviously requires variables to be enclosed in quotes.

It would make more sense for the implementer to force an integer type than the module to make (potentially incorrect) assumptions about the data type. I think this could be solved with `"{{ src | int }}"`?
